name: Publish Docker image (latest)
on:
  push:
     branches:
     # Default branches below
       - main
       - master
     paths:
      - 'deps.R'
      - 'Dockerfile'
  workflow_dispatch:
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: downcase REPO
        run: |
          echo REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.pkg.github.com/${{ github.actor }}/${{ env.REPO }}/${{ env.REPO }}:latest

